# Generated by Django 6.0.4 on 2026-04-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('program', models.CharField(choices=[('computer', 'Computer Packages'), ('catering', 'Catering'), ('baking', 'Baking & Pastry'), ('beauty', 'Beauty Therapy / Cosmetology'), ('hairdressing', 'Hairdressing'), ('barbering', 'Barbering'), ('housekeeping', 'Housekeeping & Front Office')], max_length=50)),
                ('qualification', models.CharField(choices=[('kcse', 'KCSE Certificate'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('other', 'Other')], max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
